version: '3.8'

services:
  backend:
    container_name: planning-backend
    build:
      context: ./PlanningToolBackend
    ports:
      - "8080:8080"
    networks:
      - planning-network

  frontend:
    container_name: planning-frontend
    build:
      context: ./PlanningToolFrontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - planning-network

networks:
  planning-network:
    driver: bridge
